# Generated by Django 3.2.11 on 2022-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_column_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
