# Generated by Django 3.2.11 on 2022-02-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_block_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='number',
            field=models.IntegerField(),
        ),
    ]
