# Generated by Django 3.2.11 on 2022-02-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_row_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('number', 'row')},
        ),
    ]
