# Generated by Django 3.2.11 on 2022-02-22 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_column_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='home.row'),
        ),
    ]
